#!/usr/bin/env bash
# Test with loop while FizzBuzz

i=0
while [ $i -lt 100 ]
do
    ((i++))
    if (( i % 15 == 0 ))
    then
	echo "FizzBuzz"
    elif (( i % 3 == 0 ))
    then
	echo "Fizz"
    elif (( i % 5 == 0 ))
    then
	echo "Buzz"
    else
	echo "$i"
    fi
done
