#!/usr/bin/env bash
#Conditional Statement to print 4 and 8 iteration different output

i=0
while [ $i -lt 10 ]
	do
	if [ $i -eq 4 ]
	then
	echo "bad luck"
	elif [ $i -eq 8 ]
	then
	echo "good luck"
	else
	echo "Best School"
	fi
	(( i++ ))
done 
